# Generated by Django 5.2.5 on 2025-08-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_notifieddelivery_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifieddelivery',
            old_name='customer_name',
            new_name='Addr0',
        ),
    ]
