# Generated by Django 5.2.5 on 2025-08-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_rename_customer_name_notifieddelivery_addr0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifieddelivery',
            old_name='Addr0',
            new_name='customer_name',
        ),
    ]
