# Generated by Django 5.2.5 on 2025-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0004_rename_addr0_notifieddelivery_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifieddelivery',
            old_name='notified_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='cost_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='plan_send_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='quantity_ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='reg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='reg_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='ship_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='spec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notifieddelivery',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notifieddelivery',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notifieddelivery',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
    ]
